### ISSUE TITLE
Plugin approval

### ISSUE THREAD

**Issue by NyakudyaA** [kartverket/SFKB-QGISAPI-klient#2]
# Problem

Can you please give a brief English description of what the plugin does

**Comment by andreasbaa** [comment]
We've added a short description in the QGIS description field now.

**Comment by NyakudyaA** [comment]
LGTM

**Comment by NyakudyaA** [comment]
@andreasbaa Please populate a changelog between successive upgrades of the plugin

**Comment by andreasbaa** [comment]
@NyakudyaA Added changelog now.
